# Generated by Django 5.0.6 on 2024-07-17 00:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_data(apps, schema_editor):
    # Import models from the app
    Category = apps.get_model('assets', 'Category')
    Department = apps.get_model('assets', 'Department')
    Tag = apps.get_model('assets', 'Tag')
    CustomUser = apps.get_model(settings.AUTH_USER_MODEL)
    Asset = apps.get_model('assets', 'Asset')
    Profile = apps.get_model('assets', 'Profile')
    AssetAssignment = apps.get_model('assets', 'AssetAssignment')
    AssetTag = apps.get_model('assets', 'AssetTag')

    # Create test data
    # Example for Category model
    Category.objects.create(name='Category 1')
    Category.objects.create(name='Category 2')

    # Example for Department model
    Department.objects.create(name='Department 1')
    Department.objects.create(name='Department 2')

    # Example for Tag model
    Tag.objects.create(name='Tag 1')
    Tag.objects.create(name='Tag 2')

    # Example for CustomUser model
    CustomUser.objects.create(username='user1', email='user1@example.com', firstName='First1', lastName='Last1')

    # Example for Asset model
    category1 = Category.objects.get(name='Category 1')
    department1 = Department.objects.get(name='Department 1')
    Asset.objects.create(name='Asset 1', assetType='Type 1', description='Description 1', serialNumber='123456', category=category1, assignedDepartment=department1)

    # Example for Profile model
    user1 = CustomUser.objects.get(username='user1')
    department2 = Department.objects.get(name='Department 2')
    Profile.objects.create(user=user1, role='USER', department=department2)

    # Example for AssetAssignment model
    asset1 = Asset.objects.get(name='Asset 1')
    profile1 = Profile.objects.get(user=user1)
    AssetAssignment.objects.create(asset=asset1, user=user1, assignedDepartment=department1, assignedTo=profile1)

    # Example for AssetTag model
    asset_tag1 = AssetTag.objects.create(asset=asset1, tag=Tag.objects.get(name='Tag 1'))

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customUserGroups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customUserPermissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('assetType', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('serialNumber', models.CharField(max_length=255, unique=True)),
                ('dateRecorded', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.category')),
                ('assignedDepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.department')),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateAssigned', models.DateField(auto_now_add=True)),
                ('returnDate', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assignedDepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.department')),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.profile')),
            ],
            options={
                'db_table': 'assetAssignment',
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.tag')),
            ],
            options={
                'db_table': 'assetTag',
                'unique_together': {('asset', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(through='assets.AssetTag', to='assets.tag'),
        ),
        migrations.RunPython(populate_data),  # Ensure populate_data function is defined
    ]
