# Generated by Django 5.0.6 on 2024-07-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Maintenance', 'Maintenance'), ('In use', 'In use'), ('Archived', 'Archived')], default='Available', max_length=20),
        ),
    ]
