# Generated by Django 5.0.6 on 2024-07-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetassignment',
            table='assetAssignment',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categorie',
        ),
    ]
