# Generated by Django 5.0.7 on 2024-07-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_alter_category_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="barcode_image",
            field=models.ImageField(blank=True, null=True, upload_to="barcodes/"),
        ),
        migrations.AddField(
            model_name="tag",
            name="barcode_number",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
